apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: privateapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30100
  type: NodePort